package repositories;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class HsqlRepo {
	
	public HsqlRepo() {
		
	}

	public void RepositoryBase() throws SQLException {
		Statement stmt = null;
		try {
			Class.forName("org.hsqldb.jdbcDriver");
		} catch (ClassNotFoundException e) {e.printStackTrace();}
		Connection connection = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb","sa","");
//		createTable = connection.createStatement();
	
		ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
		boolean tableExists = false;
		while (rs.next()) {
			if (tableName().equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
				tableExists = true;
				break;
			}
		}
		if (!tableExists) {
//			createTable.executeUpdate(createTableSql());
			stmt = connection.createStatement();
			rs = stmt.executeQuery(createTableSql());
		}
	
//		insert = connection.prepareStatement(insertSql());
	}
	
	protected String createTableSql() {
		return "CREATE TABLE "+tableName()+"("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "surname VARCHAR(50)," 
				+ "age int"
				+ ")";
	}

	private String tableName() {
		return "Dane";
	}
	
}
